export const API_URL = 'https://vast-journey-03684.herokuapp.com/usuario'
export const USERS_SUFFIX = 'users'
export const DEFAULT_ERROR_MESSAGE = 'Oops, something went wrong!'
export const REQUEST_ERROR_MESSAGE = 'Looks like our servers are down. We will be back soon!'
export const AUTHENTICATION_ERROR_MESSAGE = 'Authentication failed. Check your access token.'